# Generated by Django 5.0.2 on 2024-02-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('UNLISTED', 'UNLISTED'), ('FRIENDS', 'FRIENDS'), ('PUBLIC', 'PUBLIC')], default='PUBLIC', max_length=10),
        ),
    ]
