# Generated by Django 5.0.1 on 2024-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_options_post_shared_body_post_shared_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
