# Generated by Django 5.0.2 on 2024-03-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='copy_of_original_id',
            field=models.IntegerField(null=True),
        ),
    ]
