# Generated by Django 5.0.2 on 2024-03-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_copy_of_original_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
