# Generated by Django 5.0.2 on 2024-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_post_copy_of_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content_markdown',
            field=models.TextField(default=''),
        ),
    ]
