# Generated by Django 5.0.2 on 2024-03-15 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_post_content_html_post_content_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
