# Generated by Django 5.0.2 on 2024-03-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_delete_notifications'),
        ('posts', '0023_post_content_html_post_content_markdown'),
    ]

    operations = [
    ]
