# Generated by Django 5.0.2 on 2024-03-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_description_post_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
    ]
