# Generated by Django 5.0.2 on 2024-03-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content_type',
            field=models.CharField(default='text/markdown', max_length=20),
        ),
    ]
