# Generated by Django 5.0.2 on 2024-03-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_comment_content_type'),
        ('posts', '0026_post_content_type_post_origin_alter_post_description'),
    ]

    operations = [
    ]
