# Generated by Django 5.0.2 on 2024-03-17 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_likecomment'),
        ('posts', '0028_post_source_alter_post_content_type'),
    ]

    operations = [
    ]
