# Generated by Django 5.0.2 on 2024-03-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_merge_20240316_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
