# Generated by Django 5.0.2 on 2024-03-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_remove_likepost_post_id_likepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default='2024-03-19T22:37:20-06:00'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default='2024-03-19T22:37:20-06:00'),
        ),
    ]
