# Generated by Django 5.0.2 on 2024-03-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_alter_post_content_markdown'),
        ('posts', '0038_alter_comment_id'),
    ]

    operations = [
    ]
