# Generated by Django 5.0.2 on 2024-04-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0040_post_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
